=== difinition/icplayer_restore/icplayer/addons/tools/addon.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://icplayer.com" xmlns="http://icplayer.com" elementFormDefault="qualified">

    <xs:element name="addon">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="model">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" minOccurs="0" maxOccurs="unbounded" type="PropertyType" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="PropertyType">
        <xs:sequence>
            <xs:element name="property" minOccurs="0" maxOccurs="unbounded" type="PropertyType" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="nameLabel" type="xs:string"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="isLocalized">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="isDefault" type="xs:boolean" />
    </xs:complexType>

</xs:schema>

=== difinition/icplayer_restore/icplayer/addons/EdgeAnimation/src/addon.xml
<?xml version='1.0' encoding='UTF-8'?>
<addon id="EdgeAnimation" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="Animations" type="list" nameLabel="EdgeAnimation_property_animations">
			<property name="compositionClass" type="string" displayName="Composition Class" nameLabel="EdgeAnimation_property_composition_class"/>
			<property name="edgeFile" type="file" displayName="edge.js" nameLabel="EdgeAnimation_property_edge_file"/>
			<property name="edgeActionsFile" type="file" displayName="edgeActions.js" nameLabel="EdgeAnimation_property_edge_actions_file"/>
		</property>
		<property name="Images" type="list" nameLabel="EdgeAnimation_property_images">
			<property name="animationItem" type="string" displayName="Animation Item Number" nameLabel="EdgeAnimation_property_animation_item"/>
			<property name="elementId" type="string" displayName="Edge element IDs (csv)" nameLabel="EdgeAnimation_property_element_id"/>
			<property name="imageFile" type="image" displayName="Image File" nameLabel="EdgeAnimation_property_image_file"/>
		</property>
		<property name="initialAnimation" type="string" displayName="Initial Animation" nameLabel="EdgeAnimation_property_initial_animation"/>
		<property name="Narration" type="narration" nameLabel="EdgeAnimation_property_narration"/>
	</model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/Hangman/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Hangman' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="Phrases" nameLabel="Hangman_property_phrases" type="list">
			<property name="Letters" nameLabel="Hangman_property_letters" type="string" isLocalized="true" />
			<property name="Phrase" nameLabel="Hangman_property_phrase" type="string" isLocalized="true" />
		</property>
		<property name="Possible mistakes" nameLabel="Hangman_property_possible_mistakes" type="string" />
        <property name="isNotActivity" displayName="Is Not Activity" nameLabel="Hangman_property_is_not_activity" type="boolean" />
        <property name="Keyboard Letters Order" displayName="Keyboard Letters Order" nameLabel="Hangman_property_keyboard_letters_order" type="string" />
	</model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/Layered_Image/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Layered_Image' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='Base image' nameLabel="Layered_Image_property_base_image" type='image' />
		<property name="Layers" nameLabel="Layered_Image_property_layers" type="list">
			<property name="Image" nameLabel="Layered_Image_property_image" type="image" />
			<property name="Show at start" nameLabel="Layered_Image_property_show_at_start" type="boolean" />
		</property>
		<property name="Image size" nameLabel="Layered_Image_property_image_size" type="{Original, Keep aspect ratio, Stretch}" />
        <property name="Animated gif refresh" nameLabel="Layered_Image_property_animated_gif_refresh" type="boolean" />
	</model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/Grid_Scene/src/addon.xml
<?xml version="1.0" encoding="UTF-8" ?>

<addon id="Grid_Scene" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="Rows" nameLabel="Grid_Scene_property_rows" type="string" />
        <property name="Columns" nameLabel="Grid_Scene_property_columns" type="string" />
        <property name="Color" nameLabel="Grid_Scene_property_color" type="string" />
        <property name="delay" nameLabel="Grid_Scene_property_delay" type="string" />
        <property name="default_commands" nameLabel="Grid_Scene_property_default_commands" type="staticlist" isDefault="true">
            <property name="command_setColor" displayName="setColor(Color)" type="staticrow">
                <property name="alias" nameLabel="Grid_Scene_property_default_commands_command_alias" type="string"/>
                <property name="arguments_aliases" nameLabel="Grid_Scene_property_default_commands_arguments_alias" type="string"/>
                <property name="is_disabled" nameLabel="Grid_Scene_property_default_commands_is_disabled" type="boolean" />
            </property>
            <property name="command_clear" displayName="clear()" type="staticrow">
                <property name="alias" nameLabel="Grid_Scene_property_default_commands_command_alias" type="string"/>
                <property name="arguments_aliases" nameLabel="Grid_Scene_property_default_commands_arguments_alias" type="string"/>
                <property name="is_disabled" nameLabel="Grid_Scene_property_default_commands_is_disabled" type="boolean" />
            </property>
            <property name="command_setCursor" displayName="setCursor(x,y)" type="staticrow">
                <property name="alias" nameLabel="Grid_Scene_property_default_commands_command_alias" type="string"/>
                <property name="arguments_aliases" nameLabel="Grid_Scene_property_default_commands_arguments_alias" type="string"/>
                <property name="is_disabled" nameLabel="Grid_Scene_property_default_commands_is_disabled" type="boolean" />
            </property>
            <property name="command_mark" displayName="mark(x,y)" type="staticrow">
                <property name="alias" nameLabel="Grid_Scene_property_default_commands_command_alias" type="string"/>
                <property name="arguments_aliases" nameLabel="Grid_Scene_property_default_commands_arguments_alias" type="string"/>
                <property name="is_disabled" nameLabel="Grid_Scene_property_default_commands_is_disabled" type="boolean" />
            </property>
            <property name="command_clearMark" displayName="clearMark(x,y)" type="staticrow">
                <property name="alias" nameLabel="Grid_Scene_property_default_commands_command_alias" type="string"/>
                <property name="arguments_aliases" nameLabel="Grid_Scene_property_default_commands_arguments_alias" type="string"/>
                <property name="is_disabled" nameLabel="Grid_Scene_property_default_commands_is_disabled" type="boolean" />
            </property>
            <property name="command_drawLeft" displayName="drawLeft(Steps)" type="staticrow">
                <property name="alias" nameLabel="Grid_Scene_property_default_commands_command_alias" type="string"/>
                <property name="arguments_aliases" nameLabel="Grid_Scene_property_default_commands_arguments_alias" type="string"/>
                <property name="is_disabled" nameLabel="Grid_Scene_property_default_commands_is_disabled" type="boolean" />
            </property>
            <property name="command_drawUp" displayName="drawUp(Steps)" type="staticrow">
                <property name="alias" nameLabel="Grid_Scene_property_default_commands_command_alias" type="string"/>
                <property name="arguments_aliases" nameLabel="Grid_Scene_property_default_commands_arguments_alias" type="string"/>
                <property name="is_disabled" nameLabel="Grid_Scene_property_default_commands_is_disabled" type="boolean" />
            </property>
            <property name="command_drawRight" displayName="drawRight(Steps)" type="staticrow">
                <property name="alias" nameLabel="Grid_Scene_property_default_commands_command_alias" type="string"/>
                <property name="arguments_aliases" nameLabel="Grid_Scene_property_default_commands_arguments_alias" type="string"/>
                <property name="is_disabled" nameLabel="Grid_Scene_property_default_commands_is_disabled" type="boolean" />
            </property>
            <property name="command_drawDown" displayName="drawDown(Steps)" type="staticrow">
                <property name="alias" nameLabel="Grid_Scene_property_default_commands_command_alias" type="string"/>
                <property name="arguments_aliases" nameLabel="Grid_Scene_property_default_commands_arguments_alias" type="string"/>
                <property name="is_disabled" nameLabel="Grid_Scene_property_default_commands_is_disabled" type="boolean" />
            </property>
            <property name="command_drawLeftFrom" displayName="drawLeftFrom(x,y,Steps)" type="staticrow">
                <property name="alias" nameLabel="Grid_Scene_property_default_commands_command_alias" type="string"/>
                <property name="arguments_aliases" nameLabel="Grid_Scene_property_default_commands_arguments_alias" type="string"/>
                <property name="is_disabled" nameLabel="Grid_Scene_property_default_commands_is_disabled" type="boolean" />
            </property>
            <property name="command_drawUpFrom" displayName="drawUpFrom(x,y,Steps)" type="staticrow">
                <property name="alias" nameLabel="Grid_Scene_property_default_commands_command_alias" type="string"/>
                <property name="arguments_aliases" nameLabel="Grid_Scene_property_default_commands_arguments_alias" type="string"/>
                <property name="is_disabled" nameLabel="Grid_Scene_property_default_commands_is_disabled" type="boolean" />
            </property>
            <property name="command_drawRightFrom" displayName="drawRightFrom(x,y,Steps)" type="staticrow">
                <property name="alias" nameLabel="Grid_Scene_property_default_commands_command_alias" type="string"/>
                <property name="arguments_aliases" nameLabel="Grid_Scene_property_default_commands_arguments_alias" type="string"/>
                <property name="is_disabled" nameLabel="Grid_Scene_property_default_commands_is_disabled" type="boolean" />
            </property>
            <property name="command_drawDownFrom" displayName="drawDownFrom(x,y,Steps)" type="staticrow">
                <property name="alias" nameLabel="Grid_Scene_property_default_commands_command_alias" type="string"/>
                <property name="arguments_aliases" nameLabel="Grid_Scene_property_default_commands_arguments_alias" type="string"/>
                <property name="is_disabled" nameLabel="Grid_Scene_property_default_commands_is_disabled" type="boolean" />
            </property>
        </property>
        <property name="custom_commands" nameLabel="Grid_Scene_property_custom_commands" type="list">
            <property name="command_name" nameLabel="Grid_Scene_property_custom_command_name" type="string"/>
            <property name="command_arguments" nameLabel="Grid_Scene_property_custom_command_arguments" type="string"/>
            <property name="command_code" nameLabel="Grid_Scene_property_custom_command_code" type="text" />
            <property name="is_disabled" nameLabel="Grid_Scene_property_default_commands_is_disabled" type="boolean" />
        </property>
        <property name="json_commands" nameLabel="Grid_Scene_property_json_commands" type="text" />
        <property name="answer" nameLabel="Grid_Scene_property_answer" type="text" />
	</model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/Viewer_3D/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Viewer_3D' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='OBJ File' nameLabel="Viewer_3D_property_obj_file" type='file' />
		<property name='MTL File' nameLabel="Viewer_3D_property_mtl_file" type='file' />
		<property name="Initial Rotation X" nameLabel="Viewer_3D_property_initial_rotation_x" type="string" />
		<property name="Initial Rotation Y" nameLabel="Viewer_3D_property_initial_rotation_y" type="string" />
		<property name="Initial Rotation Z" nameLabel="Viewer_3D_property_initial_rotation_z" type="string" />
		<property name="Model Color" nameLabel="Viewer_3D_property_model_color" type="string" />
		<property name="Background Color 1" nameLabel="Viewer_3D_property_background_color_1" type="string" />
		<property name="Background Color 2" nameLabel="Viewer_3D_property_background_color_2" type="string" />
		<property name="Render Mode" nameLabel="Viewer_3D_property_render_mode" type="{Smooth,Points,Wireframe,Flat}" />
	</model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/Image_Viewer_Button_Controlled_Public/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Image_Viewer_Button_Controlled_Public' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='Image' nameLabel="Image_Viewer_Button_Controlled_Public_property_image" type='image' />
		<property name="Frames" nameLabel="Image_Viewer_Button_Controlled_Public_property_frames" type="string" />
		<property name="Frame size" nameLabel="Image_Viewer_Button_Controlled_Public_property_frame_size" type="{Original, Keep aspect ratio, Stretch}" />
		<property name="Sounds" nameLabel="Image_Viewer_Button_Controlled_Public_property_sounds" type="list">
			<property name="MP3 sound" nameLabel="Image_Viewer_Button_Controlled_Public_property_mp3_sound" type="audio" />
			<property name="OGG sound" nameLabel="Image_Viewer_Button_Controlled_Public_property_ogg_sound" type="audio" />
			<property name="AAC sound" nameLabel="Image_Viewer_Button_Controlled_Public_property_aac_sound" type="audio" />
		</property>
		<property name="Frame names" nameLabel="Image_Viewer_Button_Controlled_Public_property_frame_names" type="list">
			<property name="name" nameLabel="Image_Viewer_Button_Controlled_Public_property_name" type="string" />
			<property name="frame" nameLabel="Image_Viewer_Button_Controlled_Public_property_frames" type="string" />
		</property>
		<property name="isClickDisabled" nameLabel="Image_Viewer_Button_Controlled_Public_property_is_click_disabled" type="boolean" />
		<property name="Labels" nameLabel="Image_Viewer_Button_Controlled_Public_property_labels" type="list">
			<property name="Text" nameLabel="Image_Viewer_Button_Controlled_Public_property_text" type="string" isLocalized="true" />
			<property name="Top" nameLabel="Image_Viewer_Button_Controlled_Public_property_top" type="string" />
			<property name="Left" nameLabel="Image_Viewer_Button_Controlled_Public_property_left" type="string" />
			<property name="Frames" nameLabel="Image_Viewer_Button_Controlled_Public_property_frames" type="string" />
		</property>
		<property name="Show frame" nameLabel="Image_Viewer_Button_Controlled_Public_property_show_frame" type="string" />
	</model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/FigureDrawing/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='FigureDrawing' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="3DGrid" type="boolean" nameLabel="FigureDrawing_property_3d_grid" />
        <property name="ShowGrid" type="boolean" nameLabel="FigureDrawing_property_show_grid" />
        <property name="Grid" type="string" nameLabel="FigureDrawing_property_grid_step"/>
        <property name="Radius" type="string" nameLabel="FigureDrawing_property_point_radius"/>
        <property name="StartingLines" type="text" nameLabel="FigureDrawing_property_starting_lines" />
        <property name="Answer" type="text" nameLabel="FigureDrawing_property_answer" />
        <property name="IsActivity" type="boolean" nameLabel="FigureDrawing_property_is_activity" />
        <property name="IsDisabled" type="boolean" nameLabel="FigureDrawing_property_is_disabled" />
        <property name="Coloring" type="boolean" nameLabel="FigureDrawing_property_coloring" />
        <property name="DefColor" type="string" nameLabel="FigureDrawing_property_default_color" />
        <property name="StartingColors" type="text" nameLabel="FigureDrawing_property_starting_colors" />
        <property name="AnswerColors" type="list" nameLabel="FigureDrawing_property_answer_colors">
            <property name="Figure" type="string" nameLabel="FigureDrawing_property_figure" />
            <property name="Color" type="string" nameLabel="FigureDrawing_property_point_and_color" />
        </property>
        <property name="BlockColoring" type="boolean" nameLabel="FigureDrawing_property_block_coloring" />
        <property name="ShowAns" type="boolean" nameLabel="FigureDrawing_property_show_answers_in_editor" />
    </model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/Shape_Tracing/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>
<addon id='Shape_Tracing' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="Shape image" nameLabel="Shape_Tracing_property_shape_image" type="image" />
        <property name="Show Shape image" nameLabel="Shape_Tracing_property_show_shape_image" type="boolean" />
        <property name="Hide Shape image on check" nameLabel="Shape_Tracing_property_hide_shape_image_on_check" type="boolean" />
        <property name="Show Boundaries (editor)" nameLabel="Shape_Tracing_property_show_boundaries_editor" type="boolean" />
        <property name="Background image" nameLabel="Shape_Tracing_property_background_image" type="image" />
        <property name="Correct number of lines" nameLabel="Shape_Tracing_property_correct_number_of_lines" type="string" />
        <property name="Points' coordinates" nameLabel="Shape_Tracing_property_points_coordinates" type="text" />
        <property name="isPointsOrder" displayName="Mind points' order" nameLabel="Shape_Tracing_property_is_points_order" type="boolean" />
        <property name="Color" nameLabel="Shape_Tracing_property_color" type="string" />
        <property name="Pen Thickness" displayName="Thickness" nameLabel="Shape_Tracing_property_pen_thickness" type="string" />
        <property name="Opacity" nameLabel="Shape_Tracing_property_opacity" type="string" />
        <property name="Border" nameLabel="Shape_Tracing_property_border" type="string" />
        <property name="Correct Answer Image" nameLabel="Shape_Tracing_property_correct_answer_image" type="image" />
    </model>
</addon>
