=== difinition/icplayer_restore/icplayer/addons/tools/addon.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://icplayer.com" xmlns="http://icplayer.com" elementFormDefault="qualified">

    <xs:element name="addon">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="model">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" minOccurs="0" maxOccurs="unbounded" type="PropertyType" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="PropertyType">
        <xs:sequence>
            <xs:element name="property" minOccurs="0" maxOccurs="unbounded" type="PropertyType" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="nameLabel" type="xs:string"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="isLocalized">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="isDefault" type="xs:boolean" />
    </xs:complexType>

</xs:schema>

=== difinition/icplayer_restore/icplayer/addons/LearnPen_Report/src/addon.xml
<?xml version="1.0" encoding="UTF-8" ?>

<addon id="LearnPen_Report" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="isDisable" nameLabel="LearnPen_Report_property_is_disable" type="boolean" />
        <property name="correctRange" nameLabel="LearnPen_Report_property_correct_range" type="string" />
        <property name="graphType" nameLabel="LearnPen_Report_property_graph_type" type="{Pie chart, Circle in circle, Four circles, Horizontal Bar}" />
        <property name="sensor" nameLabel="LearnPen_Report_property_sensor" type="{All, Squeeze, Pressure, Squeeze A, Squeeze B, Squeeze C}" />
        <property name="colors" nameLabel="LearnPen_Report_property_colors" type="text" />
        <property name="dataUpdateInterval" nameLabel="LearnPen_Report_property_update_interval" type="string" />
        <property name="calculateFromLastValues" nameLabel="LearnPen_Report_property_get_last_values" type="string" />
    </model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/Line/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Line' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="Rotation angle" nameLabel="Line_property_rotation_angle" type="string" />
		<property name="Line width" nameLabel="Line_property_line_width" type="string" />
		<property name="Line color" nameLabel="Line_property_line_color" type="string" />
        <property name="Line opacity" nameLabel="Line_property_line_opacity" type="string" />
		<property name="Left line ending" nameLabel="Line_property_left_line_ending" type="{None, Round, Circle, Square}" />
        <property name="Right line ending" nameLabel="Line_property_right_line_ending" type="{None, Round, Circle, Square}" />
	</model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/Shooting_Range/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Shooting_Range' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="definitions" displayName="Definitions" nameLabel="Shooting_Range_property_definitions" type="list">
            <property name="definition" displayName="Definition" nameLabel="Shooting_Range_property_definition" type="html"/>
            <property name="answer1" displayName="Answer" nameLabel="Shooting_Range_property_answer" type="string" />
            <property name="answer2" displayName="Answer" nameLabel="Shooting_Range_property_answer" type="string" />
            <property name="answer3" displayName="Answer" nameLabel="Shooting_Range_property_answer" type="string" />
            <property name="correct_answers" displayName="Correct Answer(s)" nameLabel="Shooting_Range_property_correct_answer" type="string" />
        </property>
            <property name="initial_time_for_answer" displayName="Initial Time For Answer" nameLabel="Shooting_Range_property_initial_time_for_answer" type="string" />
            <property name="time_for_last_answer" displayName="Time For Last Answer" nameLabel="Shooting_Range_property_time_for_last_answer" type="string" />
    </model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/Print_Report/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Print_Report' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="Text" displayName="Text" nameLabel="Print_Report_property_text" type="string" isLocalized="true"/>
        <property name="PrintReportLabel" displayName="Print Report Label" nameLabel="Print_Report_property_print_report_label" type="string" isLocalized="true"/>
        <property name="CloseReportLabel" displayName="Close Report Label" nameLabel="Print_Report_property_close_report_label" type="string" isLocalized="true"/>
        <property name="ShowExportButton" displayName="Show Export Button" nameLabel="Print_Report_property_show_export_button" type="boolean"/>
        <property name="ExportCsvLabel" displayName="Export Button Label" nameLabel="Print_Report_property_export_csv_label" type="string" isLocalized="true"/>
        <property name="Title" displayName="Title" nameLabel="Print_Report_property_title" type="boolean"/>
        <property name="TitleLabel" displayName="Title Label" nameLabel="Print_Report_property_title_label" type="string" isLocalized="true"/>
        <property name="Subtitle" displayName="Show subtitle" nameLabel="Print_Report_property_subtitle" type="boolean"/>
        <property name="SubtitleLabel" displayName="Subtitle" nameLabel="Print_Report_property_subtitle_label" type="string" isLocalized="true"/>
        <property name="Username" displayName="Show User First And Last Name" nameLabel="Print_Report_property_username" type="boolean"/>
        <property name="PercentageScore" displayName="Percentage Score" nameLabel="Print_Report_property_percentage_score" type="boolean" />
        <property name="PercentageScoreLabel" displayName="Percentage Score Label" nameLabel="Print_Report_property_percentage_score_label" type="string" isLocalized="true"/>
        <property name="Checks" displayName="Checks" nameLabel="Print_Report_property_checks" type="boolean" />
        <property name="ChecksLabel" displayName="Checks Label" nameLabel="Print_Report_property_checks_label" type="string" isLocalized="true"/>
        <property name="Mistakes" displayName="Mistakes" nameLabel="Print_Report_property_mistakes" type="boolean" />
        <property name="MistakesLabel" displayName="Mistakes Label" nameLabel="Print_Report_property_mistakes_label" type="string" isLocalized="true"/>
        <property name="Errors" displayName="Errors" nameLabel="Print_Report_property_errors" type="boolean" />
        <property name="ErrorsLabel" displayName="Errors Label" nameLabel="Print_Report_property_errors_label" type="string" isLocalized="true"/>
        <property name="PageScore" displayName="Page Score" nameLabel="Print_Report_property_page_score" type="boolean" />
        <property name="PageScoreLabel" displayName="Page Score Label" nameLabel="Print_Report_property_page_score_label" type="string" isLocalized="true"/>
        <property name="TimePerPage" displayName="Time Per Page" nameLabel="Print_Report_property_time_per_page" type="boolean" />
        <property name="TimePerPageLabel" displayName="Time Per Page Label" nameLabel="Print_Report_property_time_per_page_label" type="string" isLocalized="true"/>
        <property name="Total" displayName="Show Total Results" nameLabel="Print_Report_property_total" type="boolean" />
        <property name="TotalLabel" displayName="Total Results Label" nameLabel="Print_Report_property_total_label" type="string" isLocalized="true"/>
        <property name="Date" displayName="Show Current Date" nameLabel="Print_Report_property_date" type="boolean" />
        <property name="DateLabel" displayName="Date Format" nameLabel="Print_Report_property_date_label" type="{dd-mm-yy, mm-dd-yy, yy-mm-dd, dd/mm/yy, mm/dd/yy, yy/mm/dd}" isLocalized="true"/>
        <property name="TimePerPageDaysLabel" displayName="Time Per Page: Days Label" nameLabel="Print_Report_property_time_per_page_days_label" type="string" isLocalized="true"/>
        <property name="TimePerPageHoursLabel" displayName="Time Per Page: Hours Label" nameLabel="Print_Report_property_time_per_page_hours_label" type="string" isLocalized="true"/>
        <property name="TimePerPageMinutesLabel" displayName="Time Per Page: Minutes Label" nameLabel="Print_Report_property_time_per_page_minutes_label" type="string" isLocalized="true"/>
        <property name="TimePerPageSecondsLabel" displayName="Time Per Page: Seconds Label" nameLabel="Print_Report_property_time_per_page_seconds_label" type="string" isLocalized="true"/>
        <property name="UsernameFirstLabel" displayName="User Form: First Name Label" nameLabel="Print_Report_property_username_first_label" type="string" isLocalized="true"/>
        <property name="UsernameLastLabel" displayName="User Form: Last Name Label" nameLabel="Print_Report_property_username_last_label" type="string" isLocalized="true"/>
        <property name="UsernameConfirmLabel" displayName="User Form: Confirm Label" nameLabel="Print_Report_property_username_confirm_label" type="string" isLocalized="true"/>
        <property name="UsernameCancelLabel" displayName="User Form: Cancel Label" nameLabel="Print_Report_property_username_cancel_label" type="string" isLocalized="true"/>
        <property name="Styles" displayName="Styles" nameLabel="Print_Report_property_styles" type="text" />
    </model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/LearnPen/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id="LearnPen" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
        <property name="SmartPen" displayName="LearnPen" nameLabel="LearnPen_property_smart_pen" type="boolean" />
        <property name="Colors" nameLabel="LearnPen_property_colors" type="text" />
        <property name="Thickness" nameLabel="LearnPen_property_thickness" type="text" />
        <property name="Opacity" nameLabel="LearnPen_property_opacity" type="text" />

        <property name="Squeeze limits" nameLabel="LearnPen_property_squeeze_limits" type="string" />
        <property name="Squeeze limits interpretation" nameLabel="LearnPen_property_squeeze_limits_interpretation" type="{Separately, Together}" />
        <property name="Pressure limits" nameLabel="LearnPen_property_pressure_limits" type="string" />

        <property name="Events" nameLabel="LearnPen_property_events" type="list">
            <property name="Sensor" nameLabel="LearnPen_property_sensor" type="string" />
            <property name="Reaction scope" nameLabel="LearnPen_property_reaction_scope" type="string" />
            <property name="Item" nameLabel="LearnPen_property_item" type="string" />
            <property name="Value" nameLabel="LearnPen_property_value" type="string" />
            <property name="Score" nameLabel="LearnPen_property_score" type="string" />
        </property>

        <property name="Mirror" nameLabel="LearnPen_property_mirror" type="boolean" />
        <property name="Background color" nameLabel="LearnPen_property_background_color" type="string" />
	</model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/Glossary/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Glossary' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='List of words' nameLabel="Glossary_property_list_of_words" type='list'>
            <property name="ID" nameLabel="Glossary_property_id" type="string" />
            <property name="Text" nameLabel="Glossary_property_text" type="string" isLocalized="true" />
            <property name="Description" nameLabel="Glossary_property_description" type="html" isLocalized="true" />
        </property>
        <property displayName="Show In Editor" name="Visible" nameLabel="Glossary_property_show_in_editor" type="boolean" />
        <property name="Open external link in" nameLabel="Glossary_property_open_external_link_in" type="{New tab, Same tab}" />
	</model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/Page_Progress_Panel/src/addon.xml
<?xml version='1.0' encoding='UTF-8'?>
<addon id="Page_Progress_Panel" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="Show_Progress_Bar" displayName="Show Progress Bar" nameLabel="Page_Progress_Panel_property_show_progress_bar" type="boolean"/>
		<property name="Progress_Bar_text" displayName="Progress Bar text" nameLabel="Page_Progress_Panel_property_progress_bar_text" type="string"/>
		<property name="Show_Correct_Answers" displayName="Show Correct Answers" nameLabel="Page_Progress_Panel_property_show_correct_answer" type="boolean"/>
		<property name="Correct_Answers_text" displayName="Correct Answers text" nameLabel="Page_Progress_Panel_property_correct_answers_text" type="string"/>
		<property name="Show_All_Answers" displayName="Show All Answers" nameLabel="Page_Progress_Panel_property_show_all_answers" type="boolean"/>
		<property name="All_Answers_text" displayName="All Answers text" nameLabel="Page_Progress_Panel_property_all_answers_text" type="string"/>
		<property name="Show_Mistakes" displayName="Show Mistakes" nameLabel="Page_Progress_Panel_property_show_mistakes" type="boolean"/>
		<property name="Mistakes_text" displayName="Mistakes text" nameLabel="Page_Progress_Panel_property_mistakes_text" type="string"/>
		<property name="Show_Checks" displayName="Show Checks" nameLabel="Page_Progress_Panel_property_show_checks" type="boolean"/>
		<property name="Checks_text" displayName="Checks text" nameLabel="Page_Progress_Panel_property_checks_text" type="string"/>
		<property name="Show_Errors" displayName="Show Errors" nameLabel="Page_Progress_Panel_property_show_errors" type="boolean"/>
		<property name="Errors_text" displayName="Errors text" nameLabel="Page_Progress_Panel_property_errors_text" type="string"/>
	</model>
</addon>
