=== difinition/icplayer_restore/icplayer/addons/tools/addon.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://icplayer.com" xmlns="http://icplayer.com" elementFormDefault="qualified">

    <xs:element name="addon">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="model">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" minOccurs="0" maxOccurs="unbounded" type="PropertyType" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="PropertyType">
        <xs:sequence>
            <xs:element name="property" minOccurs="0" maxOccurs="unbounded" type="PropertyType" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="displayName" type="xs:string"/>
        <xs:attribute name="nameLabel" type="xs:string"/>
        <xs:attribute name="type" type="xs:string" use="required"/>
        <xs:attribute name="isLocalized">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="isDefault" type="xs:boolean" />
    </xs:complexType>

</xs:schema>

=== difinition/icplayer_restore/icplayer/addons/PseudoCode_Console/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='PseudoCode_Console' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="functionsList" nameLabel="PseudoCode_Console_property_functions_list" type="list" isDefault="true">
            <property name="name" nameLabel="PseudoCode_Console_property_functions_name" type="string" />
            <property name="body" nameLabel="PseudoCode_Console_property_functions_body" type="text" />
        </property>
        <property name="methodsList" nameLabel="PseudoCode_Console_property_methods_list" type="list">
            <property name="objectName" nameLabel="PseudoCode_Console_property_object_name" type="{Number,String,Array}"/>
            <property name="methodName" nameLabel="PseudoCode_Console_property_method_name" type="string"/>
            <property name="methodBody" nameLabel="PseudoCode_Console_property_method_body" type="text"/>
        </property>
        <property name="default_aliases" nameLabel="PseudoCode_Code_property_default_aliases" type="staticlist">
            <property name="begin" displayName="Begin" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="end" displayName="End" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="variable" displayName="Variable" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="for" displayName="For" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="while" displayName="While" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="from" displayName="From" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="to" displayName="To" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="do" displayName="Do" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="program" displayName="Program" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="or" displayName="Or" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="and" displayName="And" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="if" displayName="If" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="then" displayName="Then" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="else" displayName="Else" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="case" displayName="Case" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="option" displayName="Option" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="function" displayName="Function" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="return" displayName="Return" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="array_block" displayName="Array" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="down_to" displayName="Downto" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
            <property name="by" displayName="By" type="staticrow">
                <property name="name" nameLabel="Pseudo_Console_property_functions_name" type="string" />
            </property>
        </property>
        <property name="exceptionsTranslation" nameLabel="PseudoCode_Code_property_exception_translations_list" type="staticlist">
            <property name="InstructionIsDefinedException" displayName="The instruction '{0}' has already been defined" type="staticrow">
                <property name="translation" nameLabel="Pseudo_Console_property_translation_name" type="string" />
            </property>
            <property name="CastErrorException" displayName="Cast exception '{0}' to type: '{1}'" type="staticrow">
                <property name="translation" nameLabel="Pseudo_Console_property_translation_name" type="string" />
            </property>
            <property name="GetErrorException" displayName="Exception ({0}): Value at index {1} is not defined" type="staticrow">
                <property name="translation" nameLabel="Pseudo_Console_property_translation_name" type="string" />
            </property>
            <property name="IndexOutOfBoundsException" displayName="Exception ({0}): index {1} is out of bounds" type="staticrow">
                <property name="translation" nameLabel="Pseudo_Console_property_translation_name" type="string" />
            </property>
            <property name="ToFewArgumentsException" displayName="To few arguments for function '{0}' (expected at least: {1} arguments)" type="staticrow">
                <property name="translation" nameLabel="Pseudo_Console_property_translation_name" type="string" />
            </property>
            <property name="MethodNotFoundException" displayName="Undefined method '{0}'" type="staticrow">
                <property name="translation" nameLabel="Pseudo_Console_property_translation_name" type="string" />
            </property>
            <property name="UndefinedVariableNameException" displayName="Usage of undefined variable '{0}' in function '{1}'" type="staticrow">
                <property name="translation" nameLabel="Pseudo_Console_property_translation_name" type="string" />
            </property>
            <property name="UndefinedFunctionNameException" displayName="Usage of undefined function '{0}' in function '{1}'" type="staticrow">
                <property name="translation" nameLabel="Pseudo_Console_property_translation_name" type="string" />
            </property>
            <property name="UnexpectedIdentifier" displayName="Unexpected identifier" type="staticrow">
                <property name="translation" nameLabel="Pseudo_Console_property_translation_name" type="string" />
            </property>
        </property>
        <property name="isNotActivity" nameLabel="PseudoCode_Console_property_is_not_activity" type="boolean" />
        <property name="runUserCode" nameLabel="PseudoCode_Console_property_run_user_code" type="boolean" />
        <property name="runParameters" nameLabel="PseudoCode_Console_property_run_parameters" type="list">
            <property name="value" nameLabel="PseudoCode_Console_property_parameters_value" type="string" />
        </property>
        <property name="maxTimeForAnswer" nameLabel="PseudoCode_Console_property_answer_max_timeout" type="string" />
        <property name="answerCode" nameLabel="PseudoCode_Console_property_answer_code" type="text" />
        <property name="mathRound" nameLabel="PseudoCode_Console_property_math_round" type="string"/>
        <property name="consoleAvailableInput" nameLabel="PseudoCode_Console_property_console_available_input" type="{All,Natural numbers,Real numbers,Letters only}"/>

    </model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/Page_Rating/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Page_Rating' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="Title Text" nameLabel="Page_Rating_property_title_text" type="string"/>
		<property name="Comment Text" nameLabel="Page_Rating_property_comment_text" type="string" />
		<property name="Rates" nameLabel="Page_Rating_property_rates" type="list">
            <property name="Deselected" nameLabel="Page_Rating_property_deselected" type="image"/>
		    <property name="Selected" nameLabel="Page_Rating_property_selected" type="image"/>
		</property>
        <property name="Close button visible" nameLabel="Page_Rating_property_close_button_visible" type="boolean" isLocalized="true"/>
	</model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/Show_Answers/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Show_Answers' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="Text" nameLabel="Show_Answers_property_text" type="string" isLocalized="true" />
        <property name="Text selected" nameLabel="Show_Answers_property_text_selected" type="string" isLocalized="true" />
        <property name="Increment check counter" nameLabel="Show_Answers_property_increment_check_counter" type="boolean" />
        <property name="Increment mistake counter" nameLabel="Show_Answers_property_increment_mistake_counter" type="boolean" />
        <property name="speechTexts" displayName="Speech texts" nameLabel="choice_speech_texts" type="staticlist">

            <property name="Selected" nameLabel="choice_item_selected" type="staticrow">
                <property name="Selected" nameLabel="choice_item_selected" type="string"/>
            </property>

            <property name="Block edit" nameLabel="check_answers_button_edit_block" type="staticrow">
                <property name="Block edit" nameLabel="check_answers_button_edit_block" type="string"/>
            </property>

            <property name="No block edit" nameLabel="check_answers_button_no_edit_block" type="staticrow">
                <property name="No block edit" nameLabel="check_answers_button_no_edit_block" type="string"/>
            </property>

        </property>
    </model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/MenuPanel/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>
<addon id='MenuPanel' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name="MenuItems" displayName="Menu Items" nameLabel="MenuPanel_property_menu_items" type="list" isDefault="true">
            <property name="id" displayName="Id" nameLabel="MenuPanel_property_id" type="string" />
            <property name="title" displayName="Title" nameLabel="MenuPanel_property_title" type="string" />
            <property name="parentId" displayName="Parent Id" nameLabel="MenuPanel_property_parent_id" type="string" />

            <property name="image" displayName="Image" nameLabel="MenuPanel_property_image" type="image" />

            <property name="isExpanded" displayName="Is Expanded" nameLabel="MenuPanel_property_is_expanded" type="boolean" />
            <property name="isSelected" displayName="Is Selected" nameLabel="MenuPanel_property_is_selected" type="boolean" />
            <property name="isDisabled" displayName="Is Disabled" nameLabel="MenuPanel_property_is_disabled" type="boolean" />
        </property>

        <property name="HorizontalAlignment" nameLabel="MenuPanel_property_horizontal_alignment" type="{default,left,center,right}" />
        <property name="VerticalAlignment" nameLabel="MenuPanel_property_vertical_alignment" type="{default,top,center,bottom}" />
        <property name="autoExpand" nameLabel="MenuPanel_property_auto_expand" displayName="Auto Expand" type="boolean" />
        <property name="Disable" nameLabel="MenuPanel_property_disable" type="boolean" />
    </model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/PieChart/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>
<addon id='PieChart' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
    <model>
        <property name='Items' nameLabel="PieChart_property_items" type='list' isDefault="true">
            <property name='Name' nameLabel="PieChart_property_name" type='string'/>
            <property name='Color' nameLabel="PieChart_property_color" type='string'/>
            <property name='Starting percent' nameLabel="PieChart_property_starting_percent" type='string'/>
            <property name='Answer' nameLabel="PieChart_property_answer" type='string'/>
        </property>
        <property name='Step' nameLabel="PieChart_property_step" type='string'/>
        <property name='Show values' nameLabel="PieChart_property_show_values" type='boolean'/>
        <property name='Show names' nameLabel="PieChart_property_show_names" type='boolean'/>
        <property name='Is Activity' nameLabel="PieChart_property_is_activity" type='boolean'/>
        <property name='Is Disabled' nameLabel="PieChart_property_is_disabled" type='boolean'/>
        <property name='Radius' nameLabel="PieChart_property_radius" type='string' displayName='Radius size'/>
		<property name='Percents' nameLabel="PieChart_property_percents" type='string' displayName='Percents positions'/>
    </model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/Page_Counter/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Page_Counter' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="Numericals" type="{Western Arabic,Eastern Arabic,Perso-Arabic}" nameLabel="Page_Counter_property_numericals"/>
		<property name="startFrom" type="string" nameLabel="Page_Counter_property_start_from"/>
		<property name="omittedPagesTexts" nameLabel="Page_Counter_property_omitted_pages_texts" type="list">
			<property name="pages" type="string" nameLabel="Page_Counter_property_pages"/>
			<property name="text" type="string" nameLabel="Page_Counter_property_text"/>
		</property>
		<property name="langAttribute" displayName="Lang attribute" nameLabel="Page_counter_property_lang_attribute" type="string" />
        <property name="speechTexts" displayName="Speech texts" nameLabel="Page_counter_property_speech_texts" type="staticlist">

            <property name="Page" nameLabel="Page_Counter_property_page" type="staticrow">
                <property name="Page" nameLabel="Page_Counter_property_page" type="string"/>
            </property>

            <property name="OutOf" nameLabel="Page_Counter_property_out_of" type="staticrow">
                <property name="OutOf" nameLabel="Page_Counter_property_out_of" type="string"/>
            </property>

        </property>
	</model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/SwiffyAnimation/src/addon.xml
<?xml version='1.0' encoding='UTF-8'?>
<addon id="SwiffyAnimation" xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name="Animations" type="list" nameLabel="SwiffyAnimation_property_animations">
			<property name="swiffyobject" type="file" displayName="Swiffy File" nameLabel="SwiffyAnimation_property_swiffy_object"/>
			<property name="autoPlay" type="boolean" displayName="Auto Play" nameLabel="SwiffyAnimation_property_auto_play"/>
			<property name="disableTransparentBackground" type="boolean" displayName="Disable Transparent Background" nameLabel="SwiffyAnimation_property_disable_transparent_background"/>
            <property name="doNotPreload" type="boolean" displayName="Do Not Preload" nameLabel="SwiffyAnimation_property_do_not_preload"/>
		</property>
		<property name="initialAnimation" type="string" displayName="Initial Animation" nameLabel="SwiffyAnimation_property_initial_animation"/>
	</model>
</addon>

=== difinition/icplayer_restore/icplayer/addons/Connector/src/addon.xml
<?xml version='1.0' encoding='UTF-8' ?>

<addon id='Connector' xmlns="http://icplayer.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icplayer.com ../../tools/addon.xsd">
	<model>
		<property name='Tasks' nameLabel="Connector_property_tasks" type='list'>
			<property name="Source" nameLabel="Connector_property_source" type="string" />
			<property name="Item" nameLabel="Connector_property_item" type="string" />
			<property name="Value" nameLabel="Connector_property_value" type="string" />
			<property name="Score" nameLabel="Connector_property_score" type="string" />
			<property name="Script" nameLabel="Connector_property_script" type="text" />
		</property>
	</model>
</addon>
